// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAc7k_FRGkCka70kf7H1QU3clDvGQ2gcA',
    appId: '1:856555467462:web:4ff66a60c9bcd569e4ddc7',
    messagingSenderId: '856555467462',
    projectId: 'e-chatapp-846d0',
    authDomain: 'e-chatapp-846d0.firebaseapp.com',
    storageBucket: 'e-chatapp-846d0.firebasestorage.app',
    measurementId: 'G-F1GLNXKWLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuEo1Ull0B_93mTvp359HqSqc9-W_gzgI',
    appId: '1:856555467462:android:8a39a866f5dfbdb4e4ddc7',
    messagingSenderId: '856555467462',
    projectId: 'e-chatapp-846d0',
    storageBucket: 'e-chatapp-846d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR5jU9qVsjzRBCShtewDqnhIgu94k3_qc',
    appId: '1:856555467462:ios:bc27407cc1b64b18e4ddc7',
    messagingSenderId: '856555467462',
    projectId: 'e-chatapp-846d0',
    storageBucket: 'e-chatapp-846d0.firebasestorage.app',
    iosBundleId: 'com.example.student',
  );
}
